trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/FluentCommandLine.sln'
    arguments: '--configuration $(buildConfiguration)'
